### ISSUE TITLE
Change notification library!

### ISSUE THREAD

**Issue by mrpalide** [MehdiEidi/lomodoro#1]
Hi!
Use [`martinlindhe/notify`](https://github.com/martinlindhe/notify) instead [`hey`](https://github.com/mehdieidi/hey) to make this a cross-platform tools!

**Comment by mehdieidi** [comment]
@mrpalide 
Hi Mohammad long time no see :D 

Unfortunately this library requires extra dependencies on the users machine.
"Uses the notify-send and paplay commands, both should be available on a default Ubuntu installation"

This decreases the usability of the tool.

**Comment by mrpalide** [comment]
Your're right!
What about [`beeep`](https://github.com/gen2brain/beeep)?

**Comment by mehdieidi** [comment]
This seems to work :D
Thanks for your attention.

**Comment by mrpalide** [comment]
Great. We want it on dummy :window:s machine! :laughing:

**Comment by mehdieidi** [comment]
@mrpalide 🤣

**Comment by mrpalide** [comment]
Great release!
